server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Deepakdhore/Microservice-Configuration/tree/main  # Replace with your Git repository URL
          clone-on-start: true
   profiles:
      active: local

